### PR TITLE
add aarch64 and i686 as targets

### PR DESCRIPTION
**Pull request by wucke13**

### CODE REVIEW

**Comment by wucke13** [comment]
Don't merge yet, I found a problem with this

**Comment by wucke13** [comment]
The issue was resolved.

**Comment by emilengler** [comment]
Adding support for other architectures makes syscall interception harder. Remember that the ways of how syscalls are issued are CPU dependent.

**Comment by wucke13** [comment]
> Adding support for other architectures makes syscall interception harder. Remember that the ways of how syscalls are issued are CPU dependent.

Then this issue must be resolved. We have aarch64 based development platforms and concrete use-cases for them, and we claim that "if it runs a recent linux, it works".

**Review by sevenautumns — APPROVED** [review]

**Pull request merged**
