### PR TITLE
nix: remove the release option form the example

### PR DESCRIPTION
**Pull request by emilengler**
In my opinion it makes no sense to compile an example with the release flag.

### CODE REVIEW

**Comment by dadada** [comment]
Why would one think so?

The purpose of the example is to show how to use this project in an application partition. This application would need to be deployed as an optimized object code to avoid dead code and performance issues.

**Comment by emilengler** [comment]
> Why would one think so?
> 
> 
> 
> The purpose of the example is to show how to use this project in an application partition. This application would need to be deployed as an optimized object code to avoid dead code and performance issues.

The project is primarily for development purposes anyway, thereby making debug symbols quite useful.

**Comment by wucke13** [comment]
I think we both of you are right. We should compile to release to get sweet performance, but we should include debug symbols in the release as well. This can be configure with profiles in rust, but I'm unsure about the semantics in a workspace. https://stackoverflow.com/questions/38803760/how-to-get-a-release-build-with-debugging-information-when-using-cargo contains two acceptable means of achieving this, either with a custom profile or with an env var. Which version do you two prefer, @emilengler @dadada ?

**Comment by dadada** [comment]
Yes, having similar performance, but debug symbols would be nice for development. I'd vote for using environment variables for this in this specific command.

I also see the case for debug symbols in the target that builds the hypervisor via nix. We use the hypervisor in other projects to develop partitions. If we see a crash there, it would be useful to get a clear stacktrace from RUST_BACKTRACE without fiddling with the flake inputs.

**Comment by wucke13** [comment]
Closing, as highlighted in https://github.com/DLR-FT/a653rs-linux/issues/84 there should be debug symbols already in the release build.

**Pull request closed without merging**
